### ISSUE TITLE
zabbix object no longer exists when triggers statuses are being checked

### ISSUE THREAD

**Issue by eburgueno** [velinath/zabbixweb#15]
Strange and I can't explain why, but since your latest commits, now I get the following error:
```
(index):262 Uncaught ReferenceError: zabbix is not defined
```
I'm guessing that it's because the zabbix object is not global, therefore the filterHostsAndOutput doesn't see it when invoked. Why did it work before I have no idea.

**Comment by velinath** [comment]
I'm thinking it's because $(document).ready(function() { }); wasn't there before. My bad on not catching that.

**Comment by velinath** [comment]
Thanks for the catch and the PR.
