### ISSUE TITLE
Dashboard draws fail if API call takes too long.

### ISSUE THREAD

**Issue by velinath** [velinath/zabbixweb#17]
Let's think about solutions here.

The best one that I can come up with immediately is to have each function (`filterHostsAndOutput` and `getHostsFromZabbix`) call each other, but I don't know what impact that would have if settings get changed (since `filterHostsAndOutput` is called to redraw the screen when settings change).

**Comment by eburgueno** [comment]
Would using proper AJAX (#3) have an impact in this?

**Comment by velinath** [comment]
That's a really good question. I'm still convinced that #3 is mainly a result of my incompetence, but wracking my brains for a solution hasn't helped.

I think it would fix the problem, but could cause the dashboard to refresh at irregular intervals, since the dashboard simply refreshes as soon as the API call is finished. If there's variance in API calls...

Eh. Dunno. It's certainly something to think about. I'll spend some time in the indefinite future trying to get async to work properly; we'll see how it goes!

I definitely think if we do that, we have to call `filterHostsAndOutput` as a success callback from `getHostsFromZabbix` since regardless of async, `filterHostsAndOutput` *requires* data in the hosts variable.

Feel free to correct any incorrect assumptions! :)

**Comment by velinath** [comment]
Going to go ahead and close this. Excessive load times appears to be an issue only with multiple hundreds of hosts or with Zabbix 2.2.0, which had a bug where results would take progressively longer to return from calls to the API.
