### ISSUE TITLE
Expanding "DISKS" does show name of partition/drive

### ISSUE THREAD

**Issue by smccloud** [velinath/zabbixweb#22]
This makes it really hard to determine which item is for which partition/drive.

**Comment by eburgueno** [comment]
I have the same issue in a couple of my servers. Sadly, little time to work on this, but shouldn't be too hard to figure out.

**Comment by smccloud** [comment]
@eburgueno I have tried to play around with the HTML, but all I have been able to do is break it.

**Comment by velinath** [comment]
The vfs.fs.size key from Zabbix is output as follows:

name: "Free disk space on $1"
_key: "vfs.fs.size[\/home,free]"

for sake of example.

I will work on fixing this - probably requires a code refactor at [line 241](https://github.com/velinath/zabbixweb/blob/master/index.html#L241)

**Comment by velinath** [comment]
I haven't been able to get an example for myself as far as how this returns on Windows servers, will check into that as well to make sure this won't break that reporting

**Comment by smccloud** [comment]
@velinath Do you just need some out put from zabbix_get for a windows server?

**Comment by velinath** [comment]
@smccloud - go ahead and test with latest, see if it's working for you now

**Comment by smccloud** [comment]
Works with Linux and Windows.
