### ISSUE TITLE
Host OS not detected!

### ISSUE THREAD

**Issue by heyvoon** [velinath/zabbixweb#29]
Getting "OS Unavailable" for Windows hosts.

Seems like "Template OS Windows" used "system.uname" to discover Windows OS. 

This needs to be fixed somehow on the dashboard

**Comment by velinath** [comment]
Is Zabbix able to properly detect Windows hosts now? Is there another string that we should be looking at?

Can you check your JSON output from the API for the hosts that are returning "OS Unavailable" and check the inventory.os key?

Are you running Server 2015 or a desktop OS?

**Comment by heyvoon** [comment]
My hosts are manually entered in Zabbix. And all my hosts have Zabbix agent installed. As you can see below, Zabbix report the proper OS;

![2016-03-17_13-47-22](https://cloud.githubusercontent.com/assets/3281265/13846402/1f7fa5b4-ec47-11e5-9012-de3815b6f87a.jpg)

**Comment by velinath** [comment]
can you supply the full system string? it cuts off at the end there. I need to check to see if it's a new pattern match that needs to be added

**Comment by velinath** [comment]
also, can you check your JSON output from the API for the hosts that are returning "OS Unavailable" and check the inventory.os keys? this is what the pattern match goes against, so need to make sure that string exists

**Comment by velinath** [comment]
Yeah, last comment seems accurate - it wasn't a string matching issue, it was a key issue. Latest from master might fix it

**Comment by velinath** [comment]
I'm assumign `9b594d0` fixed it, please feel free to reopen if not. I also fixed a possible bug introduced in that commit, I believe.
