### ISSUE TITLE
CPU and Memory showing weird and wrong numbers [FIXED!]

### ISSUE THREAD

**Issue by heyvoon** [velinath/zabbixweb#30]
CPU and Memory are displaying some weird numbers. I have hosts where  CPU is showing 1300% and all hosts are showing negative numbers above 100% for memory!

**This kind of make the dashboard useless!**

![2016-03-17_12-10-06](https://cloud.githubusercontent.com/assets/3281265/13844319/62119026-ec39-11e5-99ff-d2400762060d.jpg)

**Comment by velinath** [comment]
The 1300% is probably due to the number of cores not reporting correctly. If this is a Windows host, it's a known issue, but I believe it's a problem on Zabbix's end (it only reports 1 core to the dashboard).

As far as memory, I'm not sure what the problem is there. Can you look at the JSON output of free, used, etc. memory? Wondering if it's counting a swap file as well or something.

**Comment by heyvoon** [comment]
Below are some screenshots of Zabbix data for CPU and Memory on Windows hosts...

![2016-03-17_13-38-35](https://cloud.githubusercontent.com/assets/3281265/13846213/c58cc81c-ec45-11e5-9ec9-a3b48b1d62c1.jpg)

![2016-03-17_13-40-22](https://cloud.githubusercontent.com/assets/3281265/13846238/f082f60e-ec45-11e5-8e5a-ae7df231ac12.jpg)


As you can see. Zabbix is reporting correctly the number of CPUs and Memory. I think it might be something with the Math maybe.

**Comment by heyvoon** [comment]
OK! I was able to fix the "Used Memory" on the Dashboard by doing the following...

1 - Add the following key to "Template OS Linux" and "Template OS Windows";
![2016-03-17_16-20-08](https://cloud.githubusercontent.com/assets/3281265/13850933/66ced48e-ec5c-11e5-9cbc-2853dc6f07bb.jpg)

2 - Did the following modifications to the INDEX.HTML;
![2016-03-17_16-24-44](https://cloud.githubusercontent.com/assets/3281265/13851091/0b9c6d00-ec5d-11e5-85ea-95d3540b9f9e.jpg)



Note: on the code above there are some extra lines that I add trying to play around to see if I could also fix the CPU issue. So far I had no luck!

I added the following case to use CPU Utilization key;

`case 'system.cpu.util': //You may have to add this to your Zabbix templates (as float)						loadUtil = $(this)[0].lastvalue;
break;`

**Comment by velinath** [comment]
Is this related to #19 and #21?

**Comment by heyvoon** [comment]
YES! Could be! Definitely the #21 the other one I didn't read through.

**Comment by heyvoon** [comment]
Everything working as it should now on Zabbix 2.4.6 !!!   :-)

![2016-03-17_17-38-42](https://cloud.githubusercontent.com/assets/3281265/13853504/429e6e66-ec67-11e5-86ce-be0b672af339.jpg)
