### ISSUE TITLE
Error with 3.0 version of Zabbix

### ISSUE THREAD

**Issue by paumierj** [velinath/zabbixweb#33]
Hi,
Thanks for this amazing dashboard, but..
Since the last update (3.0.4) my dashboard show anything just the link setting..

There is an error of compatibility? I search with the new nersion of API but there is no fondamental update.. 

I'm lost..

Thanks

JB

**Comment by paumierj** [comment]
*I update from the 2.4 version*

**Comment by velinath** [comment]
https://github.com/velinath/zabbixweb/blob/master/index.html#L162 - change to 3.0.4 instead of 3.0.1. Does the dashboard work if you do that?

**Comment by paumierj** [comment]
No it's doesn't work.. I try with a clean VM and reinstall Ubuntu and Zabbix with the 3.0.4 version and this is the same pb. The 3.0.1 version is working?

**Comment by paumierj** [comment]
*thanks for your reponse*

**Comment by velinath** [comment]
Try commenting out the entire referenced if block and trying again. Thank you.

**Comment by velinath** [comment]
Should be fixed in d0ffd44, if I hear nothing in the next couple days I will close.

**Comment by yiching** [comment]
I just clone the latest code, but still didn't work. My zabbix version is 3.0.5.

**Comment by velinath** [comment]
can you open your developer tools and see if there are any errors being thrown?

**Comment by yiching** [comment]
<img width="1230" alt="screen shot 2016-11-18 at 8 57 12 am" src="https://cloud.githubusercontent.com/assets/4469564/20414375/1206dc30-ad6d-11e6-9da2-5b50a54fcfbd.png">

**Comment by velinath** [comment]
Check the network tab, if length is undefined it sounds like data isn't getting returned from zabbix if I had to guess.

**Comment by yiching** [comment]
Yes. But how to get data from zabbix? I've changed `var zabbix = new $.zabbix ('http://zabbix.org/zabbix/api_jsonrpc.php', 'guest', '')` to my zabbix server information. Are there any other thing I have to do?

**Comment by velinath** [comment]
Right. You would need to check and see what the code being returned is from the AJAX request.

**Comment by velinath** [comment]
Try it now! I just pushed a new change.
