### ISSUE TITLE
Index.html showing plain black screen

### ISSUE THREAD

**Issue by jashankochar** [velinath/zabbixweb#34]
i have configured the way u described but when am opening the url it is displaying bllank screen
![error](https://cloud.githubusercontent.com/assets/17452611/22963345/b0a72c68-f378-11e6-8219-218ffa77354c.PNG)

**Comment by eburgueno** [comment]
@jashankochar can you post a diff between the index on the repo and the one you have? do mask the username and password before posting.

**Comment by jashankochar** [comment]
index.html is same as i have just configured var zabbix with my zabbix server /zabbix/api_jsonrpc.php ,
nothing else i changed

**Comment by eburgueno** [comment]
@jashankochar the reason I was asking was just to make sure you didn't accidentally leave out a quotiation mark or something like that.

But looking at your console error in more details, it appears that the Zabbix API call is not returning you any hosts. Are you able to see any response headers and/or data in the Network tab? Also, what version of Zabbix are you running?

**Comment by jashankochar** [comment]
3.2 for zabbix versions

**Comment by velinath** [comment]
I think @eburgueno is probably on the right track, can you post what's in your Network tab when you load the page? Wondering what the API call to Zabbix is returning, or whether this might be a CORS issue.

**Comment by velinath** [comment]
Looks like a blog commenter may have solved this one. https://www.andrewletson.com/building-better-zabbix-frontend/#comment-30

It looks like, in the latest version, the string comparison between the Zabbix API versoin and the string '2.4' is failing.

My vote is to branch the old version and call it a day, which I've now done. Please pull latest from master and give it another shot.

**Comment by Solved-IT** [comment]
Yes, it probably has something to do with detecting the API version. The latest commit is a dirty fix for this but it will only work on API version > 2.4.

Perhaps this is worth mentioning in the readme.md?

**Comment by velinath** [comment]
Yeah, it's forked to `pre-3.0` for older versions. I'll make a note in readme.md for those still running older versions of Zabbix.

**Comment by jashankochar** [comment]
@velinath , sorry for late replying that day i discovered this problem and solved.
For api call it was calling user.authenticate by default , which i corrected by deleting that part and keeping user.login and it works. Thanks. And i will surely contribute more to this repo in coming days.
