### ISSUE TITLE
Disks may mix "used" and "total" values from different FSs

### ISSUE THREAD

**Issue by eburgueno** [velinath/zabbixweb#7]
Right now we are blindly storing pfree, used and total into an array, without ensuring the values on each index all belong to the same filesystem. We can't rely on the order the Zabbix API returns each item.
We need to add some smarts. I suggest something like:
```
thisHostObj.disks(index,'fs_name','pfree','used','total')
```

Matrices are hard :(

**Comment by velinath** [comment]
I've blocked out some time to research and address this this weekend, will update then.

**Comment by velinath** [comment]
Sorry I've been late on this. Still on my radar, just extraordinarily busy - took on some more responsibilities elsewhere. If you have time to get a PR together it'd be awesome.

**Comment by eburgueno** [comment]
I've been busy as well lately. Will try to tackle this one but doesn't seem to be causing too much trouble so far. Maybe the API is well behaved and returns results "in order".

**Comment by velinath** [comment]
I think it does from my testing. I've tried with a few different Windows and Linux distros with multiple-disk configurations and haven't had it return incorrect results yet. Maybe we can just close this one with the caveat that we may need to revisit if Zabbix regresses in the future?

**Comment by eburgueno** [comment]
We can leave it open but on low priority. I wouldn't make any assumptions about the API without going through the trouble of reading the code (ain't nobody got time fo dat).

**Comment by velinath** [comment]
Works for me!

**Comment by velinath** [comment]
Looked into this further, and made sure that things will work without us doing anything in particular. Each disk gets assigned an ID and they are returned in order. Doesn't look like 3.0 will change this behavior so we can close this.
